language: python
python:
  - "3.7"

services:
  - docker

install:
  - docker build -t oidclab .
  - docker run -d -p 8000:8000 --name oidclab oidclab

before_script:
  - pip install -r requirements.txt

script:
  - docker ps | grep -q oidclab
# - python oidc-lab.py
  
